name: CarPrices_env
channels:
  - defaults
dependencies:
  - python=3.8
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - imbalanced-learn
  - mlflow
  - pip:
      - matplotlib
